title: Alok Dath # your name (or website title) here
logo: "/images/logo_3.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Systems Software Engineer
  <br><br>
I have 8.5 years of experience in IT industry with good understanding in application maintenance and operations support and currently I am working as Systems Support Engineer.Senior Lead at Akamai Technologies
   <br><br>
  <a href="https://in.linkedin.com/in/alok-dath-1b911333">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
